server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    platform: mysql
    url: jdbc:p6spy:mysql://127.0.0.1:3306/freestyle?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  # redis
  redis:
    database: 0
    host: 127.0.0.1
    password: ''
    port: 6379
    timeout: 10000ms
    lettuce:
      pool:
        max-idle: 8
        max-wait: 2000ms
        min-idle: 0

# mybatis plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: cn.tellsea.freestyle.system.entity
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 2
    banner: false

# freestyle
freestyle:
  swagger:
    enabled: true
    version: 1.0
    author: tellsea
    url: https://github.com/tellsea
    email: 3210054449@qq.com
    description: 更多项目：https://github.com/tellsea
    termsOfServiceUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  shiro:
    jwtTokenTimeOut: 3600

