server:
  port: 8080
spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    db1:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://47.107.171.232:3306/freestyle?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
      username: root
      password: Root123!@#
      db-type: mysql
      validation-query: "select 1"
      max-active: 16
      min-idle: 4
    db2:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://47.107.171.232:3306/freestyle_test?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
      username: root
      password: Root123!@#
      db-type: mysql
      validation-query: "select 1"
    druid:  # druid 监控配置
      filter:
        stat:
          enabled: true  #是否激活sql监控
        wall:
          enabled: true  #是否激活sql防火墙
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"   #浏览器访问localhost:8080/druid，进入监控界面
        login-username: admin
        login-password: admin@123

  # redis
  redis:
    database: 0
    host: 127.0.0.1
    password: ''
    port: 6379
    timeout: 10000ms
    lettuce:
      pool:
        max-idle: 8
        max-wait: 2000ms
        min-idle: 0

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# mybatis plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: cn.tellsea.freestyle.system.entity
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 2
    banner: false

# freestyle
freestyle:
  swagger:
    enabled: true
    version: 1.0
    author: tellsea
    url: https://github.com/tellsea
    email: 3210054449@qq.com
    description: 更多项目：https://github.com/tellsea
    termsOfServiceUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  shiro:
    jwtTokenTimeOut: 3600

